name: Build and Test with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and start services with Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d --build

      - name: Run tests in Node.js container
        run: docker exec api-testing-js-app npm test

      - name: Tear down services
        run: docker-compose down
